# Generated by Django 2.1.5 on 2019-02-18 08:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_student_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2019, 2, 18, 8, 27, 21, 207822, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
